- name: Install AWS CLI
  raw: "apt-get -y -q install awscli"
  become: true

- name: Download kubectl binaries
  get_url:
    url: "{{ kubernetes_download_path }}/{{ item }}"
    dest: "/usr/bin"
    group: root
    owner: root
    mode: 0755
  with_items:
    - kubectl
  become: true

- name: Create .kube folder
  file: 
    path: "/home/ubuntu/.kube"
    owner: ubuntu
    state: directory
    recurse: yes
    mode: 0755
  become: true

- name: Add Kubelet configuration client
  template:
    src: kubeconfig.j2
    dest: /home/ubuntu/.kube/config
    mode: 0755
  become: true


 
- name: Find and delete all blackholes
  shell: |
          aws ec2 describe-route-tables --route-table-id "{{ kubernetes_route_table_id }}" --filters "Name=route.state,Values=blackhole" --query 'RouteTables[0].Routes[?State == `blackhole`]' | jq -r ".[].DestinationCidrBlock" | while read cidr ; do
            aws ec2 delete-route --route-table-id "{{ kubernetes_route_table_id }}" --destination-cidr-block "$cidr"
          done
  ignore_errors: yes
  become: true


- name: Gather Kubernetes nodes facts
  shell: kubectl get nodes --output=json --output=jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address},{.spec.podCIDR}{"\n"}{end}'
  register: net
  become: true
  become_user: ubuntu
 
- name: Update routes
  shell: |
          echo "{{net.stdout}}" | tr " " "\n" |  while read item ; do  
            IP=$(echo $item | cut -d ',' -f 1)
            CIDR=$(echo $item | cut -d ',' -f 2)
            NETWORK_INTERFACE=$(aws ec2 describe-instances --filters "Name=private-ip-address,Values=$IP" --query 'Reservations[0].Instances[0].NetworkInterfaces[0].NetworkInterfaceId' --output text)
            echo "$NETWORK_INTERFACE - $IP - $CIDR"
            aws ec2 create-route --route-table-id "{{ kubernetes_route_table_id }}" --network-interface-id $NETWORK_INTERFACE --destination-cidr-block "$CIDR"
          done
  ignore_errors: yes
  become: true



- name: Copy kube-dns files
  template:
    src: "{{ item }}.j2"
    dest: "/home/ubuntu/{{ item }}"
    mode: 700
  become: true
  with_items:
    - kube-dns-s.yaml
    - kube-dns-rc.yaml

- name: Apply kube-dns files
  shell: kubectl apply -f /home/ubuntu/{{ item }}
  with_items:
    - kube-dns-s.yaml
    - kube-dns-rc.yaml
  become: true
  become_user: ubuntu








