- hosts: all
  gather_facts: false
  tasks:
    - name: Install Python
      raw: "apt-get -y -q install python"
      become: true
- hosts: etcd
  roles:
    - etcd
- hosts: controller
  roles:
    - controller
- hosts: worker
  roles:
    - worker