- hosts: all
  gather_facts: false
  tasks:
    - name: Install Python
      raw: "apt-get -y -q install python"
      become: true
  roles:
    - franklinkim.newrelic
  vars:
    newrelic_service_state: started
    newrelic_disable_docker: false
    ansible_os_family: Debian
  become: true
- hosts: etcd
  roles:
    - etcd
- hosts: controller
  roles:
    - controller
- hosts: worker
  roles:
    - worker
- hosts: deployer
  environment:
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  roles:
    - deployer
